# ==============================================================================
# =====================  workstations  =========================================
# ==============================================================================

ws: 100
sh: 50
co: 20 # container_box_blue / container_box_red
pp: 10
cb: 0

# ==============================================================================
# ======================  objects  =============================================
# ==============================================================================

long objects
f20_20_b: 20
f20_20_g: 20
s40_40_b: 20
s40_40_g: 20
m20_100: 20
axis: 20

# medium objects
r20: 20
m30: 20
motor: 20
bearing_box: 20

# small objects
distance_tube: 10
bearing: 10
m20: 10