variables:
  ROS_RELEASE: indigo
  REPOSITORY_NAME: mas_industrial_robotics

before_script:
  - rm -rf build devel install
  - rm -rf $CI_PROJECT_DIR/../src
  - rm -rf $CI_PROJECT_DIR/../*.tmp
  - source /opt/ros/$ROS_RELEASE/setup.bash

stages:
  - build

build:
  stage: build
  script:
    - export ROBOT=youbot-brsu-1
    - export ROBOT_ENV=brsu-c025-sim
    - git pull gitgate@mas.b-it-center.de:mas-group/$REPOSITORY_NAME.git $ROS_RELEASE
    - mkdir -p $CI_PROJECT_DIR/../src
    - cd $CI_PROJECT_DIR/..
    - cp -r $REPOSITORY_NAME src
    - mv src $REPOSITORY_NAME
    - cd $CI_PROJECT_DIR/src/$REPOSITORY_NAME
    - if [ -f repository.debs ]; then ./repository.debs false ; fi
    - cd $CI_PROJECT_DIR/src
    - git clone -b $ROS_RELEASE gitgate@mas.b-it-center.de:mas-group/mas_datasets.git
    - cd $CI_PROJECT_DIR
    - catkin_make -Dyoubot_driver_ros_interface_USE_SETCAP=OFF
    - source $CI_PROJECT_DIR/devel/setup.bash
    - catkin_make tests
    - catkin_make roslint
    - catkin_lint --strict src/
    - catkin_make install
    - catkin_make run_tests
    - catkin_test_results
