1.pregrasp_planner:
    event_in_topic: /mir_manipulation/pregrasp_planner_pipeline/event_in
    event_in_strings: [e_start, e_stop]
    event_out_topic: /mir_manipulation/pregrasp_planner_pipeline/event_out
2.planned_arm_motion:
    event_in_topic: /mir_manipulation/move_arm_planned/event_in
    event_in_strings: [e_start, e_stop]
    event_out_topic: /mir_manipulation/move_arm_planned/event_out
