model:
  squeezeDet:
    image:
      width: 640
      height: 480
    bbox_prob_output_to_keep: 0.4
  SSDLiteMobileNet:
classes:
  0: 'S40_40_G'
  1: 'S40_40_B'
  2: 'R20'
  3: 'MOTOR'
  4: 'M30'
  5: 'M20_100' 
  6: 'M20'
  7: 'F20_20_G' 
  8: 'F20_20_B'
  9: 'EM-02'
  10: 'EM-01' 
  11: 'DISTANCE_TUBE' 
  12: 'CONTAINER_BOX_RED'
  13: 'CONTAINER_BOX_BLUE' 
  14: 'BEARING_BOX'
  15: 'BEARING_BOX'
  16: 'BEARING'
  17: 'AXIS'
colors:
  0: (0, 0, 255) 
  1: (0, 0, 255)
  2: (0, 0, 255)
  3: (0, 0, 255)
  4: (0, 0, 255) 
  5: (0, 0, 255) 
  6: (0, 0, 255)
  7: (255, 191, 0) 
  8: (0, 0, 255)
  9: (0, 0, 255) 
  10: (0, 0, 255) 
  11: (0, 0, 255) 
  12: (0, 0, 255)
  13: (0, 0, 255) 
  14: (0, 0, 255)
  15: (0, 0, 255)
  16: (0, 0, 255)
  17: (0, 0, 255)