local_costmap:
  global_frame: /map
  robot_base_frame: base_footprint
  update_frequency: 2.0
  publish_frequency: 1.0
  static_map: false
  rolling_window: true
  width: 2.5
  height: 2.5
  resolution: 0.01
  origin_x: 0.0
  origin_y: 0.0
