#-------------SPEED----------------------------

max_trans_vel: 0.8              #default : 0.55
min_trans_vel: 0.1              #default : 0.1

max_vel_x: 0.7                  #default : 0.55
min_vel_x: -0.07                 #default : 0.0

max_vel_y: 0.1                  #default : 0.1
min_vel_y: -0.1                 #default : -0.1

max_rot_vel: 0.75                #default : 1.0
min_rot_vel: 0.2                #default : 0.4

acc_lim_x: 1.5                  #default : 2.5
acc_lim_y: 1.5                  #default : 2.5
acc_lim_theta: 1.5              #default : 3.2
acc_limit_trans: 0.5            #default : 0.1

#----------------------------------------------

sim_time: 1.7                   #default : 0.8
sim_granularity: 0.025          #default : 0.025

goal_distance_bias: 14.0        #default : 24.0
path_distance_bias: 35.0        #default : 32.0

occdist_scale: 0.01             #default : 0.01

stop_time_buffer: 0.2           #default : 0.2
oscillation_reset_dist: 0.05    #default : 0.05

forward_point_distance: 0.25    #default : 0.325

scaling_speed: 0.35             #default : 0.25
max_scaling_factor: 0.2         #default : 0.2

vx_samples: 6                   #default : 3
vy_samples: 3                   #default : 10
vtheta_samples: 15              #default : 20

sim_period: 0.2                 #default : not found

xy_goal_tolerance: 0.2        #default : 0.10
yaw_goal_tolerance: 0.1         #default : 0.05
latch_xy_goal_tolerance: true   #default : false

rot_stopped_vel: 0.01           #default : not found
trans_stopped_vel: 0.01         #default : not found

penalize_negative_x: false      #default : true
