map_type: costmap           # default: "voxel"
#transform_tolerance: 0.2   # default: 0.2
obstacle_range: 2.5         # default: 2.5 
raytrace_range: 3.0         # default: 3.0
footprint: [[-0.2720, -0.1869],
            [-0.2720, -0.0331],
            [-0.3260, -0.0310],
            [-0.3260, 0.0310],
            [-0.2720, 0.0325],
            [-0.2720, 0.1875],
            [0.2720, 0.1875],
            [0.2720, 0.0865],
            [0.3160, 0.0425],
            [0.3160, -0.0425],
            [0.2720, -0.0865],
            [0.2720, -0.1875]]

observation_sources: laser_scanner_front laser_scanner_rear

laser_scanner_front: {sensor_frame: base_laser_front_link, data_type: LaserScan, topic: /scan_front, expected_update_rate: 1.2, observation_persistence: 0.0,  marking: true, clearing: true, min_obstacle_height: -0.10, max_obstacle_height: 2.0}
# default sensor_frame : ""
# default data_type : "PointCloud"
# default topic : "PointCloud", "PointCloud2", or "LaserScan"
# default expected_update_rate : 0.0
# default observation_persistence : 0.0
# default marking : true
# default clearing : false
# default min_obstacle_height : 0.0
# default max_obstacle_height: 2.0

laser_scanner_rear: {sensor_frame: base_laser_rear_link, data_type: LaserScan, topic: /scan_rear, expected_update_rate: 1.2, observation_persistence: 0.0,  marking: true, clearing: true, min_obstacle_height: -0.10, max_obstacle_height: 2.0}
# default sensor_frame : ""
# default data_type : "PointCloud"
# default topic : "PointCloud", "PointCloud2", or "LaserScan"
# default expected_update_rate : 0.0
# default observation_persistence : 0.0
# default marking : true
# default clearing : false
# default min_obstacle_height : 0.0
# default max_obstacle_height: 2.0
