local_costmap:
  global_frame: /map                    #default : "/map"
  inflation_radius: 0.46                #default: 0.55
  robot_base_frame: base_footprint      #default : "base_link"
  update_frequency: 2.0                 #default : 5.0
  publish_frequency: 2.0                #default : 0.0
  static_map: false                     #default : true
  rolling_window: true                  #default : false
  width: 2.5                            #default : 10
  height: 2.5                           #default : 10
  resolution: 0.02                      #default : 0.05
  footprint_padding: 0.02               #default : 0.01
