local_costmap:
  global_frame: /odom
  robot_base_frame: base_footprint
  update_frequency: 5.0
  publish_frequency: 0.0
  static_map: false
  rolling_window: true
  width: 10.0
  height: 6.0
  resolution: 0.04
